services:
  api:
    build: ./API/
    command: sh -c "sleep 10s ; python3 app.py"
    depends_on:
      - mysql

  front:
    build: ./Frontend/
    command: sh -c "sleep 10s ; python3 app.py"
    depends_on:
      - api
    ports:
        - "5000:5000"

  mysql:
    build: ./API/database/
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 'pass'
        MYSQL_DATABASE: 'adminprop'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pass'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: pass
    depends_on:
      - mysql